name: warungku_app
description: "WarungKu Digital - Aplikasi Kasir UMKM"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.12.0
  
  # State Management (tanpa code generation untuk stabilitas)
  flutter_riverpod: ^3.2.0
  
  # Navigation
  go_router: ^17.0.1
  
  # UI & Styling
  google_fonts: ^7.0.2
  
  # Utilities
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^6.1.4
  
  # Media
  image_picker: ^1.2.1
  
  # PDF Generation
  pdf: ^3.11.3
  printing: ^5.14.2
  uuid: ^4.5.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/launcher_icon_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
